package com.example.superheroesapp.ui.theme

import androidx.compose.ui.graphics.Color

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
//
//val Purple40 = Color(0xFF6650a4)
//val PurpleGrey40 = Color(0xFF625b71)
//val Pink40 = Color(0xFF7D5260)



val md_theme_light_primary = Color(0xFF006D42)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF92F7BC)
val md_theme_light_onPrimaryContainer = Color(0xFF002111)
val md_theme_light_secondary = Color(0xFF216C2E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFA7F5A7)
val md_theme_light_onSecondaryContainer = Color(0xFF002106)
val md_theme_light_tertiary = Color(0xFF006A68)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF6FF7F3)
val md_theme_light_onTertiaryContainer = Color(0xFF00201F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF404942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF76DAA1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D42)
val md_theme_light_outlineVariant = Color(0xFFC0C9C0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF76DAA1)
val md_theme_dark_onPrimary = Color(0xFF003920)
val md_theme_dark_primaryContainer = Color(0xFF005231)
val md_theme_dark_onPrimaryContainer = Color(0xFF92F7BC)
val md_theme_dark_secondary = Color(0xFF8BD88D)
val md_theme_dark_onSecondary = Color(0xFF00390F)
val md_theme_dark_secondaryContainer = Color(0xFF00531A)
val md_theme_dark_onSecondaryContainer = Color(0xFFA7F5A7)
val md_theme_dark_tertiary = Color(0xFF4DDAD7)
val md_theme_dark_onTertiary = Color(0xFF003736)
val md_theme_dark_tertiaryContainer = Color(0xFF00504E)
val md_theme_dark_onTertiaryContainer = Color(0xFF6FF7F3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF404942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006D42)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF76DAA1)
val md_theme_dark_outlineVariant = Color(0xFF404942)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF58BB85)